raudit/config/routes.rb
Rails.application.routes.draw do

  resources :estado_plans
  resources :paquetes_plan_to_fechas
  get 'paquetes/plan'
  resources :paquete_plan_to_procedimientos
  get 'paquetes/asignar'
  resources :paquete_plans
  get 'password_resets/new'
  get 'password_resets/edit'
  resources :users
  get 'sessions/new'
  resources :riesgos
  resources :procedimientos
  resources :procesos
  resources :tipo_objetivos
  resources :estados
  resources :centros
  resources :tipo_procesos
  get 'main/menu'
  get 'getEstados' => 'estados#getEstados'
  post 'getEstados' => 'estados#getEstados'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
  	get '/get_tprocedimientos' ,  to: 'tipo_procedimientos#get_Tipo'
    get 'getpaquetes' => 'tipo_procedimientos#get_paquetes'
    get 'getproceso' => 'tipo_procedimientos#get_procesos'
    get 'getprocedimientos' => 'tipo_procedimientos#get_procedimientos'
    get 'getprocedimientos_x_proceso' => 'tipo_procedimientos#get_procedimiento_x_procesos'
    get 'setpaquetes_x_procedimiento' => 'tipo_procedimientos#set_paquetes_x_procedimientos'
    get 'getprocedimiento_x_paquete' => 'tipo_procedimientos#get_procedimiento_x_paquete'
    get 'delprocedimiento_paquete' => 'tipo_procedimientos#eliminar_procedimiento_x_paquete'
    get 'plan' => 'tipo_procedimientos#get_plan_auditoria'
  end 


  # usuario para logearme 
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'signup'  => 'users#new'

  # activacion por correo electronico
  resources :account_activations, only: [:edit]
  # reset de la clave a traves del correo electronico
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

raudit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

raudit/app/models/centro.rb
class Centro < ApplicationRecord
end

raudit/app/models/estado.rb
class Estado < ApplicationRecord
end

raudit/app/models/estado_plan.rb
class EstadoPlan < ApplicationRecord
end

raudit/app/models/paquete_plan.rb
class PaquetePlan < ApplicationRecord
end

raudit/app/models/procedimiento.rb
class Procedimiento < ApplicationRecord
	self.primary_key = 'id'
	#has_many :PaquetePlanToProcedimiento, class_name: "PaquetePlanToProcedimiento", foreing_key: "idprocedimiento"
end

raudit/app/models/proceso.rb
class Proceso < ApplicationRecord
end

raudit/app/models/riesgo.rb
class Riesgo < ApplicationRecord
end

raudit/app/models/tipo_objetivo.rb
class TipoObjetivo < ApplicationRecord
end

raudit/app/models/tipo_proceso.rb
class TipoProceso < ApplicationRecord
end

raudit/app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token , :activation_token, :reset_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  #
  before_save   :downcase_email
  before_create :create_activation_digest


  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    puts attribute
    puts token
    puts '**************************************'
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

 # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

# Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end


  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

   private 

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

raudit/app/controllers/centros_controller.rb
class CentrosController < ApplicationController
  before_action :set_centro, only: [:show, :edit, :update, :destroy]

  # GET /centros
  # GET /centros.json
  def index
    @centros = Centro.all
  end

  # GET /centros/1
  # GET /centros/1.json
  def show
  end

  # GET /centros/new
  def new
    @centro = Centro.new
  end

  # GET /centros/1/edit
  def edit
  end

  # POST /centros
  # POST /centros.json
  def create
    @centro = Centro.new(centro_params)

    respond_to do |format|
      if @centro.save
        format.html { redirect_to @centro, notice: 'Centro was successfully created.' }
        format.json { render :show, status: :created, location: @centro }
      else
        format.html { render :new }
        format.json { render json: @centro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /centros/1
  # PATCH/PUT /centros/1.json
  def update
    respond_to do |format|
      if @centro.update(centro_params)
        format.html { redirect_to @centro, notice: 'Centro was successfully updated.' }
        format.json { render :show, status: :ok, location: @centro }
      else
        format.html { render :edit }
        format.json { render json: @centro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /centros/1
  # DELETE /centros/1.json
  def destroy
    @centro.destroy
    respond_to do |format|
      format.html { redirect_to centros_url, notice: 'Centro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_centro
      @centro = Centro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def centro_params
      params.require(:centro).permit(:nombre, :estados_id)
    end
end

raudit/app/controllers/main_controller.rb
class MainController < ApplicationController
  def menu
  end
end

raudit/app/helpers/application_helper.rb
module ApplicationHelper
end

raudit/app/helpers/centros_helper.rb
module CentrosHelper
end

raudit/app/helpers/estado_plans_helper.rb
module EstadoPlansHelper
end

raudit/app/helpers/estados_helper.rb
module EstadosHelper
end

raudit/app/helpers/main_helper.rb
module MainHelper
end

raudit/app/helpers/paquetes_helper.rb
module PaquetesHelper
end

raudit/app/helpers/procesos_helper.rb
module ProcesosHelper
end

raudit/app/helpers/riesgos_helper.rb
module RiesgosHelper
end

raudit/app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

raudit/app/helpers/users_helper.rb
module UsersHelper
end

raudit/app/views/centros/_form.html.erb
<%= form_with(model: centro, local: true) do |form| %>
  <% if centro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(centro.errors.count, "error") %> prohibited this centro from being saved:</h2>

      <ul>
      <% centro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :estados_id %>
    <%= form.collection_select(:estados_id, Estado.all, :id, :descripcion) %>
  </div>

  <div class="actions">
    <%= form.submit  class: "btn btn-primary"%>
  </div>
<% end %>

raudit/app/views/centros/edit.html.erb
<h1>Editar Centros</h1>

<%= render 'form', centro: @centro %>

<%= link_to 'Mostrar', @centro %> |
<%= link_to 'Atras', centros_path %>

raudit/app/views/centros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Centros</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Estados</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @centros.each do |centro| %>
      <tr>
        <td><%= centro.nombre %></td>
        <% @Resultado = Estado.where(id:centro.estados_id)
        @Resultado.each do |row| %>
           <td><%= row.descripcion %></td>
        <%end %>  
        <td><%= link_to 'Mostrar', centro %></td>
        <td><%= link_to 'Editar', edit_centro_path(centro) %></td>
        <td><%= link_to 'Eliminar', centro, method: :delete, data: { confirm: 'Estas seguro que deseas Eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Centro', new_centro_path %>

raudit/app/views/centros/new.html.erb
<h1>Nuevo Centro</h1>

<%= render 'form', centro: @centro %>

<%= link_to 'Atras', centros_path %>

raudit/app/views/centros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @centro.nombre %>
</p>

<p>
  <strong>Estados:</strong>
  

  <% @Resultado = Estado.where(id:@centro.estados_id)
  @Resultado.each do |row| %>
        <%= row.descripcion %>
  <%end %>  
</p>

<%= link_to 'Editar', edit_centro_path(@centro) %> |
<%= link_to 'Atras', centros_path %>