raudit/config/routes.rb
Rails.application.routes.draw do

  resources :estado_plans
  resources :paquetes_plan_to_fechas
  get 'paquetes/plan'
  resources :paquete_plan_to_procedimientos
  get 'paquetes/asignar'
  resources :paquete_plans
  get 'password_resets/new'
  get 'password_resets/edit'
  resources :users
  get 'sessions/new'
  resources :riesgos
  resources :procedimientos
  resources :procesos
  resources :tipo_objetivos
  resources :estados
  resources :centros
  resources :tipo_procesos
  get 'main/menu'
  get 'getEstados' => 'estados#getEstados'
  post 'getEstados' => 'estados#getEstados'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
  	get '/get_tprocedimientos' ,  to: 'tipo_procedimientos#get_Tipo'
    get 'getpaquetes' => 'tipo_procedimientos#get_paquetes'
    get 'getproceso' => 'tipo_procedimientos#get_procesos'
    get 'getprocedimientos' => 'tipo_procedimientos#get_procedimientos'
    get 'getprocedimientos_x_proceso' => 'tipo_procedimientos#get_procedimiento_x_procesos'
    get 'setpaquetes_x_procedimiento' => 'tipo_procedimientos#set_paquetes_x_procedimientos'
    get 'getprocedimiento_x_paquete' => 'tipo_procedimientos#get_procedimiento_x_paquete'
    get 'delprocedimiento_paquete' => 'tipo_procedimientos#eliminar_procedimiento_x_paquete'
    get 'plan' => 'tipo_procedimientos#get_plan_auditoria'
  end 


  # usuario para logearme 
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'signup'  => 'users#new'

  # activacion por correo electronico
  resources :account_activations, only: [:edit]
  # reset de la clave a traves del correo electronico
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

raudit/app/models/tipo_objetivo.rb
class TipoObjetivo < ApplicationRecord
end

raudit/app/controllers/tipo_objetivos_controller.rb
class TipoObjetivosController < ApplicationController
  before_action :set_tipo_objetivo, only: [:show, :edit, :update, :destroy]

  # GET /tipo_objetivos
  # GET /tipo_objetivos.json
  def index
    @tipo_objetivos = TipoObjetivo.all
  end

  # GET /tipo_objetivos/1
  # GET /tipo_objetivos/1.json
  def show
  end

  # GET /tipo_objetivos/new
  def new
    @tipo_objetivo = TipoObjetivo.new
  end

  # GET /tipo_objetivos/1/edit
  def edit
  end

  # POST /tipo_objetivos
  # POST /tipo_objetivos.json
  def create
    @tipo_objetivo = TipoObjetivo.new(tipo_objetivo_params)

    respond_to do |format|
      if @tipo_objetivo.save
        format.html { redirect_to @tipo_objetivo, notice: 'Tipo objetivo was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_objetivo }
      else
        format.html { render :new }
        format.json { render json: @tipo_objetivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_objetivos/1
  # PATCH/PUT /tipo_objetivos/1.json
  def update
    respond_to do |format|
      if @tipo_objetivo.update(tipo_objetivo_params)
        format.html { redirect_to @tipo_objetivo, notice: 'Tipo objetivo was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_objetivo }
      else
        format.html { render :edit }
        format.json { render json: @tipo_objetivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_objetivos/1
  # DELETE /tipo_objetivos/1.json
  def destroy
    @tipo_objetivo.destroy
    respond_to do |format|
      format.html { redirect_to tipo_objetivos_url, notice: 'Tipo objetivo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_objetivo
      @tipo_objetivo = TipoObjetivo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_objetivo_params
      params.require(:tipo_objetivo).permit(:descripcion, :estado)
    end
end

raudit/app/helpers/tipo_objetivos_helper.rb
module TipoObjetivosHelper
end

raudit/app/views/tipo_objetivos/_form.html.erb
<%= form_with(model: tipo_objetivo, local: true) do |form| %>
  <% if tipo_objetivo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipo_objetivo.errors.count, "error") %> prohibited this tipo_objetivo from being saved:</h2>

      <ul>
      <% tipo_objetivo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.collection_select(:estado, Estado.all, :id, :descripcion) %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

raudit/app/views/tipo_objetivos/edit.html.erb
<h1>Editar Tipo Objetivo</h1>

<%= render 'form', tipo_objetivo: @tipo_objetivo %>

<%= link_to 'Mostrar', @tipo_objetivo %> |
<%= link_to 'Atras', tipo_objetivos_path %>

raudit/app/views/tipo_objetivos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipo Objetivos</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_objetivos.each do |tipo_objetivo| %>
      <tr>
        <td><%= tipo_objetivo.descripcion %></td>
        <% @Resultado = Estado.where(id:tipo_objetivo.estado)
        @Resultado.each do |row| %>
        <td><%= row.descripcion %></td>
         <%end %>        
        <td><%= link_to 'Mostrar', tipo_objetivo %></td>
        <td><%= link_to 'Editar', edit_tipo_objetivo_path(tipo_objetivo) %></td>
        <td><%= link_to 'Eliminar', tipo_objetivo, method: :delete, data: { confirm: 'Estas seguro que desea eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Tipo Objetivo', new_tipo_objetivo_path %>

raudit/app/views/tipo_objetivos/new.html.erb
<h1>Nuevo Tipo Objetivo</h1>

<%= render 'form', tipo_objetivo: @tipo_objetivo %>

<%= link_to 'Atras', tipo_objetivos_path %>

raudit/app/views/tipo_objetivos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @tipo_objetivo.descripcion %>
</p>

<p>
  <strong>Estado:</strong>
  <% @Resultado = Estado.where(id:@tipo_objetivo.estado)
  @Resultado.each do |row| %>
        <%= row.descripcion %>
  <%end %>       
</p>

<%= link_to 'Editar', edit_tipo_objetivo_path(@tipo_objetivo) %> |
<%= link_to 'Atras', tipo_objetivos_path %>