raudit/config/routes.rb
Rails.application.routes.draw do

  resources :estado_plans
  resources :paquetes_plan_to_fechas
  get 'paquetes/plan'
  resources :paquete_plan_to_procedimientos
  get 'paquetes/asignar'
  resources :paquete_plans
  get 'password_resets/new'
  get 'password_resets/edit'
  resources :users
  get 'sessions/new'
  resources :riesgos
  resources :procedimientos
  resources :procesos
  resources :tipo_objetivos
  resources :estados
  resources :centros
  resources :tipo_procesos
  get 'main/menu'
  get 'getEstados' => 'estados#getEstados'
  post 'getEstados' => 'estados#getEstados'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
  	get '/get_tprocedimientos' ,  to: 'tipo_procedimientos#get_Tipo'
    get 'getpaquetes' => 'tipo_procedimientos#get_paquetes'
    get 'getproceso' => 'tipo_procedimientos#get_procesos'
    get 'getprocedimientos' => 'tipo_procedimientos#get_procedimientos'
    get 'getprocedimientos_x_proceso' => 'tipo_procedimientos#get_procedimiento_x_procesos'
    get 'setpaquetes_x_procedimiento' => 'tipo_procedimientos#set_paquetes_x_procedimientos'
    get 'getprocedimiento_x_paquete' => 'tipo_procedimientos#get_procedimiento_x_paquete'
    get 'delprocedimiento_paquete' => 'tipo_procedimientos#eliminar_procedimiento_x_paquete'
    get 'plan' => 'tipo_procedimientos#get_plan_auditoria'
  end 


  # usuario para logearme 
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'signup'  => 'users#new'

  # activacion por correo electronico
  resources :account_activations, only: [:edit]
  # reset de la clave a traves del correo electronico
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

raudit/app/models/paquete_plan_to_procedimiento.rb
class PaquetePlanToProcedimiento < ApplicationRecord
end

raudit/app/controllers/paquete_plan_to_procedimientos_controller.rb
class PaquetePlanToProcedimientosController < ApplicationController
  before_action :set_paquete_plan_to_procedimiento, only: [:show, :edit, :update, :destroy]

  # GET /paquete_plan_to_procedimientos
  # GET /paquete_plan_to_procedimientos.json
  def index
    @paquete_plan_to_procedimientos = PaquetePlanToProcedimiento.all
  end

  # GET /paquete_plan_to_procedimientos/1
  # GET /paquete_plan_to_procedimientos/1.json
  def show
  end

  # GET /paquete_plan_to_procedimientos/new
  def new
    @paquete_plan_to_procedimiento = PaquetePlanToProcedimiento.new
  end

  # GET /paquete_plan_to_procedimientos/1/edit
  def edit
  end

  # POST /paquete_plan_to_procedimientos
  # POST /paquete_plan_to_procedimientos.json
  def create
    @paquete_plan_to_procedimiento = PaquetePlanToProcedimiento.new(paquete_plan_to_procedimiento_params)

    respond_to do |format|
      if @paquete_plan_to_procedimiento.save
        format.html { redirect_to @paquete_plan_to_procedimiento, notice: 'Paquete plan to procedimiento was successfully created.' }
        format.json { render :show, status: :created, location: @paquete_plan_to_procedimiento }
      else
        format.html { render :new }
        format.json { render json: @paquete_plan_to_procedimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paquete_plan_to_procedimientos/1
  # PATCH/PUT /paquete_plan_to_procedimientos/1.json
  def update
    respond_to do |format|
      if @paquete_plan_to_procedimiento.update(paquete_plan_to_procedimiento_params)
        format.html { redirect_to @paquete_plan_to_procedimiento, notice: 'Paquete plan to procedimiento was successfully updated.' }
        format.json { render :show, status: :ok, location: @paquete_plan_to_procedimiento }
      else
        format.html { render :edit }
        format.json { render json: @paquete_plan_to_procedimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paquete_plan_to_procedimientos/1
  # DELETE /paquete_plan_to_procedimientos/1.json
  def destroy
    @paquete_plan_to_procedimiento.destroy
    respond_to do |format|
      format.html { redirect_to paquete_plan_to_procedimientos_url, notice: 'Paquete plan to procedimiento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paquete_plan_to_procedimiento
      @paquete_plan_to_procedimiento = PaquetePlanToProcedimiento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paquete_plan_to_procedimiento_params
      params.require(:paquete_plan_to_procedimiento).permit(:idpaquete, :idprocedimiento)
    end
end

raudit/app/helpers/paquete_plan_to_procedimientos_helper.rb
module PaquetePlanToProcedimientosHelper
end

raudit/app/views/paquete_plan_to_procedimientos/_form.html.erb
<%= form_with(model: paquete_plan_to_procedimiento, local: true) do |form| %>
  <% if paquete_plan_to_procedimiento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paquete_plan_to_procedimiento.errors.count, "error") %> prohibited this paquete_plan_to_procedimiento from being saved:</h2>

      <ul>
      <% paquete_plan_to_procedimiento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :idpaquete %>
    <%= form.text_field :idpaquete %>
  </div>

  <div class="field">
    <%= form.label :idprocedimiento %>
    <%= form.text_field :idprocedimiento %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

raudit/app/views/paquete_plan_to_procedimientos/edit.html.erb
<h1>Editar Procedimiento de los paquetes</h1>

<%= render 'form', paquete_plan_to_procedimiento: @paquete_plan_to_procedimiento %>

<%= link_to 'Mostrar', @paquete_plan_to_procedimiento %> |
<%= link_to 'Atras', paquete_plan_to_procedimientos_path %>

raudit/app/views/paquete_plan_to_procedimientos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Paquete Plan con Procedimientos</h1>

<table>
  <thead>
    <tr>
      <th>Idpaquete</th>
      <th>Idprocedimiento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paquete_plan_to_procedimientos.each do |paquete_plan_to_procedimiento| %>
      <tr>
        <td><%= paquete_plan_to_procedimiento.idpaquete %></td>
        <td><%= paquete_plan_to_procedimiento.idprocedimiento %></td>
        <td><%= link_to 'Show', paquete_plan_to_procedimiento %></td>
        <td><%= link_to 'Edit', edit_paquete_plan_to_procedimiento_path(paquete_plan_to_procedimiento) %></td>
        <td><%= link_to 'Destroy', paquete_plan_to_procedimiento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Procedimiento de Paquete', new_paquete_plan_to_procedimiento_path %>

raudit/app/views/paquete_plan_to_procedimientos/new.html.erb
<h1>New Paquete Plan To Procedimiento</h1>

<%= render 'form', paquete_plan_to_procedimiento: @paquete_plan_to_procedimiento %>

<%= link_to 'Atras', paquete_plan_to_procedimientos_path %>

raudit/app/views/paquete_plan_to_procedimientos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idpaquete:</strong>
  <%= @paquete_plan_to_procedimiento.idpaquete %>
</p>

<p>
  <strong>Idprocedimiento:</strong>
  <%= @paquete_plan_to_procedimiento.idprocedimiento %>
</p>

<%= link_to 'Editar', edit_paquete_plan_to_procedimiento_path(@paquete_plan_to_procedimiento) %> |
<%= link_to 'Atras', paquete_plan_to_procedimientos_path %>